/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dell' at '15-12-31 上午8:55' with Gradle 2.6
 *
 * @author dell, @date 15-12-31 上午8:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
